{"name": "test_register_existing_user_failed", "status": "passed", "description": "Повторная регистрация того же пользователя должна возвращать ошибку 403.", "start": 1752679620917, "stop": 1752679623858, "uuid": "14c12576-196a-4b07-99d7-b88d7f48c6f9", "historyId": "9dcde1051b0444c738b4135575159596", "testCaseId": "9dcde1051b0444c738b4135575159596", "fullName": "tests.test_user_register.TestUserRegister#test_register_existing_user_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_register"}, {"name": "subSuite", "value": "TestUserRegister"}, {"name": "host", "value": "MacBook-Pro-3.local"}, {"name": "thread", "value": "2184-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_register"}]}